version: '3.1'

services:
  itvanti-chatbot:
    # image: itvanti/chatbot:business
    image: itvanti/bot-itvanti:business
    restart: always
    environment:
      - PORT=${PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_URI=${MONGODB_URI}

      - ITVANTI_BOT_PUBLIC_URL=${ITVANTI_BOT_PUBLIC_URL}
      - ITVANTI_BOT_USE_WAB=${ITVANTI_BOT_USE_WAB}

      - PINECONE_ENV=${PINECONE_ENV}
      - PINECONE_PROJECT_ID=${PINECONE_PROJECT_ID}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ITVANTI_BOT_INDEX=${PINECONE_ITVANTI_BOT_INDEX}

      - STABLE_DIFFUSION_API_KEY=${STABLE_DIFFUSION_API_KEY}
      - STABLE_DIFUSSION_WEBHOOK_IMAGINE=${STABLE_DIFUSSION_WEBHOOK_IMAGINE}
      - LEONARDO_API_KEY=${LEONARDO_API_KEY}
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      - REPLICATE_WEBHOOK=${REPLICATE_WEBHOOK}

      - WA_SYNC_INTERVAL=${WA_SYNC_INTERVAL}
      - WA_CHATBOT_NAME=${WA_CHATBOT_NAME}

      - AZURE_CS_REGION=${AZURE_CS_REGION}
      - AZURE_CS_RESOURCE_KEY=${AZURE_CS_RESOURCE_KEY}
      - AZURE_CS_VOICE=${AZURE_CS_VOICE}
      - AZURE_SEARCH_KEY=${AZURE_SEARCH_KEY}
      - AZURE_LANG_ENDPOINT=${AZURE_LANG_ENDPOINT}
      - AZURE_LANG_REGION=${AZURE_LANG_REGION}
      - AZURE_LANG_KEY=${AZURE_LANG_KEY}

      - WA_BUSINESS_TOKEN=${WA_BUSINESS_TOKEN}
      - WA_BUSINESS_APP=${WA_BUSINESS_APP}
      - WA_BUSINESS_VERIFY_TOKEN=${WA_BUSINESS_VERIFY_TOKEN}
      - WA_BUSINESS_PHONE_ID=${WA_BUSINESS_PHONE_ID}
      - WA_BUSINESS_PHONE_NUMBER=${WA_BUSINESS_PHONE_NUMBER}
      - WA_BUSINESS_GRAPH_API=${WA_BUSINESS_GRAPH_API}
      - PHONE_ADMINS=${PHONE_SU_ADMINS}

      - NODE_ENV="production"
      - WA_BOT_SHOW_DETAIL_LOGS=false
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ~/.itvanti:/root/.itvanti
    # command: /bin/sh -c "sleep 3; flowise start"